remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: Data science portfolio (STAT-228)
author: Jenn Leishman
description: |
  Data science portfolio with work from STAT-228

